-- MySQL Script generated by MySQL Workbench
-- Mon Dec 23 10:18:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookstore` ;

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`bookinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`bookinfo` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`bookinfo` (
  `id_book` INT(11) NOT NULL,
  `picture_book` VARCHAR(100) NULL DEFAULT NULL,
  `name_ch_book` VARCHAR(100) NULL DEFAULT NULL,
  `name_en_book` VARCHAR(100) NULL DEFAULT NULL,
  `author_ch_book` VARCHAR(100) NULL DEFAULT NULL,
  `author_en_book` VARCHAR(100) NULL DEFAULT NULL,
  `price_book` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_book`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('1', 'img/book/28470639-1_l_5.jpg', '自游加州全攻略', 'The complete tour of California', ' 李·福斯特', 'Lee foster', '18.7');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('2', 'img/book/25197810-1_l_3.jpg', '尤尔小屋的猫', "The cat at jul's house.", ' 莉莉·海沃德', 'Lily hayward.', '14.4');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('3', 'img/book/25546541-1_l_9.jpg', '空间简史', 'A brief history of space', ' 托马斯·马卡卡罗', 'Thomas makorro', '19.9');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('4', 'img/book/28470981-1_l_3.jpg', '谜案鉴赏', 'Connoisseur of mysteries', ' 莉比·菲舍尔·赫尔曼', 'Libby fischer Herman.', '17.8');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('5', 'img/book/25141508-1_l_3.jpg', '朝圣者', 'The pilgrim', ' 泰瑞·海耶斯', 'Terry hayes', '24.6');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('6', 'img/book/27911444-1_l_3.jpg', '高尔基成长三部曲（童年、在人间、我的大学）', "Gorky's growth trilogy (childhood, on earth, my university)", ' 高尔基', 'Gorky', '37.8');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('7', 'img/book/27869583-1_l_2.jpg', '向上管理：与你的领导相互成就', 'Managing up: achieving mutual success with your leader', ' 萧雨', 'Tuiop', '19.9');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('8', 'img/book/27939503-1_l_3.jpg', '焦虑日志', 'Anxiety journal', ' 柯瑞妮·斯威特', 'Corrine. Sweet', '19.4');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('9', 'img/book/27941577-1_l_3.jpg', '谎言心理学', 'Psychology of lies', ' 米兰达·道尔', 'Miranda Doyle', '15.5');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('10', 'img/book/28470980-1_l_5.jpg', '阴谋与爱情', 'Intrigue and love', ' J·B·卞若琳', 'JB. Caroline', '14.2');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('11', 'img/book/27914171-1_l_3.jpg', '我的前半生', 'The first half of my life', ' 爱新觉罗·溥仪', 'Aisin gioro puyi', '47.4');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('12', 'img/book/27898768-1_l_1.jpg', '假如给我三天光明', 'Give me three days to see.', ' 海伦·凯勒', 'Helen Keller', '12');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('13', 'img/book/24157581-1_l_15.jpg', '魔力四射：如何打动、亲近和影响他人', 'Be magical: how to move, approach, and influence others', ' 帕特里克·金', 'Patrick king', '12.5');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('14', 'img/book/28475555-1_l_4.jpg', '永久记录', 'Permanent record', ' 爱德华·斯诺登', 'Edward snowden', '23.5');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('15', 'img/book/28477052-1_l_8.jpg', '成瘾：如何设计让人上瘾的产品、品牌和观念', 'Addiction: how to design addictive products, brands, and ideas', ' 程志良', 'Cheng zhiliang', '40.7');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('16', 'img/book/24157582-1_l_13.jpg', '脱口而出', 'Blurt it out.', ' 安德里·赛德涅夫', 'Endree seidnev.', '17.6');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('17', 'img/book/25069964-1_l_19.jpg', '旋木情缘', 'Turning wood love', ' 堂娜·法萨诺', 'Donna fasano.', '13.6');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('18', 'img/book/25069963-1_l_16.jpg', '呐喊――大屠杀回忆录', 'The scream -- memoirs of the holocaust', ' 曼尼·斯坦伯格', 'Manny steinberg', '13.6');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('19', 'img/book/26914210-1_l_2.jpg', '愤怒的葡萄', 'The grapes of wrath', ' 约翰·斯坦贝克', 'John Steinbeck', '22.6');
INSERT INTO `bookstore`.`bookinfo` (`id_book`, `picture_book`, `name_ch_book`, `name_en_book`, `author_ch_book`, `author_en_book`, `price_book`) VALUES ('20', 'img/book/28489455-1_l_3.jpg', '热爱', 'Love', ' 宋方金', 'Song fangjin', '32.2');


-- -----------------------------------------------------
-- Table `bookstore`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`car` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`car` (
  `name_user` VARCHAR(45) NOT NULL,
  `id_book` VARCHAR(45) NOT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `picture_book` VARCHAR(200) NULL DEFAULT NULL,
  `name_ch_book` VARCHAR(45) NULL DEFAULT NULL,
  `name_en_book` VARCHAR(45) NULL DEFAULT NULL,
  `author_ch_book` VARCHAR(45) NULL DEFAULT NULL,
  `author_en_book` VARCHAR(45) NULL DEFAULT NULL,
  `price_book` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`name_user`, `id_book`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookstore`.`userinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`userinfo` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`userinfo` (
  `name_user` VARCHAR(15) NOT NULL,
  `pwd_user` VARCHAR(32) NOT NULL,
  `address_user` VARCHAR(100) NULL DEFAULT NULL,
  `gender_user` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`name_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
